theme: jekyll-theme-cayman
custom_css:
  - /assets/css/custom.css
title: Çiçek Güven 
github:
  is_project_page: false
description: Assistant Professor, Department of Cognitive Science and Artificial Intelligence, Tilburg University
#baseurl: ""
#url: "https://cicekguven.github.io"  # Update this with your site URL


buttons:
      zip_url: http://example.com/
      zip_title: Title
      zip_hide: true
      tar_url: http://example.com/
      tar_title: Title
      tar_hide: true
      github_hide: true # hides "View on Github"



# Navigation links
nav_links:
  - title: "Home"
    url: /
  - title: "projects"
    url: /projects/
  - title: "diversity and inclusion"
    url: /diversityandinclusion/
  - title: "contact"
    url: /contact/
 





